# Problem 2
#
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
#
# @date 11/03/2012 
# @author Ciarán McCann
# @website http://ciaranmccann.me/

def fibEvenSummation():
	sum = 0
	p1 = 0
	p2 = 1
	while p2+p1 < 4000000:
		p1 = p1 + p2
		p2 = p1 + p2
		
		if p1 % 2 == 0:
			sum += p1
		if p2 % 2 == 0:
			sum += p2

	return sum



print(fibEvenSummation())